---
title: "Экзамен"
subtitle: "Современные методы анализа данных // РАНХиГС"
format: html
editor: source
theme: materia
---

Максимальное количество баллов --- 40.

## Вариант 1

Для анализа Вам предлагаются данные об результатах «быстрых свиданий» (speed dating). Исследователи хотят знать, какие факторы оказываются решающими при формировании пары по итогам «быстрых свиданий».

[Датасет](https://drive.google.com/uc?export=download&id=1Cl1P7eo7K98ny0gpb-hClbGFk_FNO3G5)

[Описание переменных](https://drive.google.com/uc?export=download&id=16Kf66eJb1bZv_bOisyY9DIK7NesWLuAs)

* Предобработайте данные, если это необходимо.
* Сформулируйте гипотезы и возможном влиянии факторов на формирование пары по итогам свиданий. Вы можете использовать как результаты разведочного анализа, так и теоретические основания.
* Подберите способ (модель) анализа для проверки сформулированных гипотез. Обоснуйте выбор модели.
* Постройте выбранную модель. Визуализируйте её. Оцените качество модели и выполнение математических допущений. Опишите ограничения модели. Дайте рекомендации по её улучшению.
* Протестируйте заявленные гипотезы. Опишите полученные результаты.
* Проинтерпретируйте полученные результаты. Вы можете использовать собственные общие и специальные знания, а также при необходимости привлечь соответствующую теорию.


## Вариант 2

Для анализа Вам предлагаются HR-данные о сотрудниках большой компании. Руководители хотят знать, какие факторы приводят к истощению сотрудников.

[Датасет](https://drive.google.com/uc?export=download&id=1Zwi86WY9lLpObsPRMzxatAm7JadGUDTe)

Описание переменных находится на втором листе файла с данными

* Предобработайте данные, если это необходимо.
* Исследуйте данные. Сформулируйте гипотезы и возможном влиянии факторов на истощение сотрудников. Вы можете использовать как результаты разведочного анализа, так и теоретические основания.
* Подберите способ (модель) анализа для проверки сформулированных гипотез. Обоснуйте выбор модели.
* Постройте выбранную модель. Визуализируйте её. Оцените качество модели и выполнение математических допущений. Опишите ограничения модели. Дайте рекомендации по её улучшению.
* Протестируйте заявленные гипотезы. Опишите полученные результаты.
* Проинтерпретируйте полученные результаты. Вы можете использовать собственные общие и специальные знания, а также при необходимости привлечь соответствующую теорию.


## Критерии оценки

* **K1 --- Качество скрипта (max 4)**
    * Код понятен, обладает высокой удобочитаемостью, содержит комментарии. Отсутствует избыточность кода --- 4
    * Код понятен, обладает высокой удобочитаемостью, но отсутствуют комментарии ИЛИ есть незначительная избыточность --- 3
    * Чтение кода затруднено, отсутствуют комментарии, есть избыточность кода --- 2
    * Чтение кода значительно затруднено, присутствует значительная избыточность, отсутствуют комментарии --- 1
    * Код нечитаемый --- 0
* **K2 --- Вопроизводимость скрипта (max 4)**
    * Скрипт воспроизводится без ошибок --- 4
    * Скрипт воспроизводится с незначительными ошибками, несущественными для понимания хода анализа, ошибки не влияют на результаты анализа --- 3
    * Скрипт воспроизводится с ошибками, сложно понять ход анализа, но ошибки не влияют на результаты анализа --- 2
    * Скрипт воспроизводится с ошибками, ошибки влияют на результаты анализа --- 1
    * Код не воспроизводится --- 0
* **K3 --- Разведочный анализ (max 4)**
    * Корректно проведен разведочный анализ, сделаны корректные выводы по результатам анализа --- 4
    * Проведен разведочный анализ, однако в процедуре ИЛИ выводах по результатам присутствуют несущественные недочеты --- 3
    * Проведен разведочный анализ, однако в процедуре И выводах по результатам присутствуют несущественные недочеты --- 2
    * Разведочный анализ проведен с существенными недочетами --- 1
    * Разведочный анализ не проведен --- 0
* **K4 --- Формулирование гипотез (max 2)**
    * Гипотезы сформулированы верно с опорой на результаты разведочного анализа И теоретические основания --- 2
    * Гипотезы сформулированы верно с опорой на результаты разведочного анализа ИЛИ теоретические основания --- 1
    * Гипотезы не сформулированы --- 0
* **K5 --- Выбор метода (max 4)**
    * Выбран корректный метод анализа, соответствующий заявленным гипотезам, представлено достаточное обоснование выбора метода --- 4
    * Выбран корректный метод анализа, соответствующий заявленным гипотезам, однако представлено частичное обоснование выбора --- 3
    * Выбран корректный метод анализа, соответствующий заявленным гипотезам, однако обоснование выбора отсутствует --- 2
    * Выбран метод анализа, частично соответствующий заявленным гипотезам --- 1
    * Выбран метод анализа, не соответствующий заявленным гипотезам --- 0
* **K6 --- Процедура анализа (max 5)**
    * Процедура анализа корректна, отсутствуют ошибки и неточности --- 5
    * роцедура анализа корректна, но содержит незначительные неточности --- 4
    * Ход процедуры анализа корректный, однако есть ОДИН ИЛИ ДВА существенных недочета --- 3
    * В процедуре анализа есть ОДНА ГРУБАЯ ошибка --- 2
    * В процедуре анализа есть БОЛЕЕ ОДНОЙ ГРУБОЙ ошибки --- 1
    * Анализ не проведен --- 0
* **K7 --- Интерпретация результатов (max 4)**
    * Интерпретация результатов корректно, отсутствуют ошибки и неточности --- 4
    * Интерпретация результатов корректно, но содержат незначительные неточности --- 3
    * Интерпретация результатов содержит ОДНУ ГРУБУЮ ошибку --- 2
    * Интерпретация результатов содержит БОЛЕЕ ОДНОЙ ГРУБОЙ ошибки --- 1
    * Интерпретация результатов отсутствует --- 0
* **K8 --- Визуалиации (max 5)**
    * Все визуализации, представленные в отчете, выполнены корректно --- 5
    * В отчете представлены необходимые визуализации, однако в них есть несущественные недочеты --- 4
    * В отчете представлены необходимые визуализации, однако в ОДНОЙ ИЛИ ДВУХ есть существенный недочет --- 3
    * В визуализациях присутствует ОДНА ГРУБАЯ СИСТЕМАТИЧЕСКАЯ ошибка --- 2
    * В визуализациях присутствует БОЛЕЕ ОДНОЙ ГРУБОЙ ошибки --- 1
    * Визуализации отсутствуют --- 0
* **K9 --- Оценка модели (max 4)**
    * Оценка модели проведена корректно, представленная интерпретация не содержит ошибок и неточностей --- 4
    * Оценка модели проведена корректно, представленная интерпретация содержит незначительные неточности --- 3
    * Оценка модели проведена корректно, представленная интерпретация содержит ошибки --- 2
    * Оценка модели проведени некорректно --- 1
    * Оценка модели отсутствует --- 0
* **K10 --- Предложения по улучшению модели (max 4)**
    * Представленные предложения достаточно обоснованы, опираются на данные, разведочный анализ, результаты анализа и оценки модели --- 4
    * Представленные предложения частично обоснованы --- 3
    * Представленные предложения не обоснованы --- 2
    * Представленные предложения некорретны с точки зрения статистических моделей --- 1
    * Предложения по улучшению модели не представлены --- 0