---
title: "КР3 // Обобщенные линейные модели"
subtitle: "Современные методы анализа данных // РАНХиГС"
format: html
editor: source
theme: materia
---

Максимальное количество баллов --- 20 (+3 дополнительных за задание 10.1)

Сегодня мы работаем с [датасетом про ноутбуки](https://raw.githubusercontent.com/angelgardt/hseuxlab-wlm2021/master/data/laptop_price.csv), который содержит следующие переменные:

* `Company` --- компания-производитель компьютера
* `Product` --- бренд и модель
* `TypeName` --- тип ноутбука (Notebook, Ultrabook, Gaming, etc.)
* `Inches` --- размер экрана
* `ScreenResolution` --- разрешение экрана
* `Cpu` --- характеристики процессора
* `Ram` --- размер оперативной памяти
* `Memory` --- память жёсткого диска
* `GPU` --- характеристики графического процессора
* `OpSys` --- операционная система
* `Weight` --- вес компьютера
* `Price_euros` --- цена в Евро


```{r, include=FALSE}
library(tidyverse)
theme_set(theme_bw())
```


## 1

Загрузите [датасет](https://raw.githubusercontent.com/angelgardt/hseuxlab-wlm2021/master/data/laptop_price.csv). Проверьте типы переменных. Если есть такие переменные, которые по своему содержанию должны быть другого типа, приведите их к нужному типу. Сделайте необходимые преобразования с переменными, если они потребуются.

<details>
<summary>*Подсказка*</summary>
Обратите внимание, как записаны переменные `Cpu`, `Ram`, `Memory` и `Weight`.
</details>


## 2

Исследуйте взаимосвязи между ценой и характеристиками ноутбуков. Предположите, какие переменные могли бы быть включены в регрессионную модель в качестве предикторов.



## 3

Постройте линейную модель со случайным интерсептом, которая позволит ответить на глобальный вопрос к данным: как зависит цена компьютера от его технических характеристик? В модель должны быть включены _минимум два_ фиксированных эффекта. В качестве случайного эффекта включите в модель группировку по компании-производителю.



## 4

Проведите диагностику модели. Проверьте её статистическую значимость, а также индуцированные корреляции. Сделайте выводы на основе результатов диагностики. (2 балла)

<details>
<summary>*Пояснение*</summary>
Обычно нас интересует прежде всего интересует фиксированная часть модели, поэтому сосредоточтесь на ней.
</details>


## 5

Проведите анализ остатков модели. Сделайте заключение о качестве модели на основе результатов анализа. (1 балл)

<details>
<summary>*Пояснение*</summary>
Графической диагностики будет достаточно.
</details>


## 6

Протестируйте статистическую значимость предикторов с помощью тестов Вальда. Интерпретируйте результаты.


## 7

Протестируйте статистическую значимость предикторов с помощью тестов отношения правдоподобий. Интерпретируйте результаты. Сравните их с результатами тестов Вальда.


## 8

Усложните случайную часть модели. Возьмите за основу имеющуюся модель, но добавьте ещё один случайный интерсепт. Группирующую переменную выберите самостоятельно.


## 9

Протестируйте статистическую значимость введенного случайного интерсепта. Сравните две модели с тестом отношения правдоподобий для случайных эффектов. Интерпретируйте результаты.

<details>
<summary>*Подсказка*</summary>
Обратите внимание на способ подбора модели.
</details>


## 10

Постройте модель обычной линейной регрессии с такой же структурой предикторов. Сравните предсказательную силу модели обычной линейной регрессии и модели с одним случайным интерсептом. Какая модель даёт более точные предсказания?

<details>
<summary>*Пояснение*</summary>
Достаточно сравнить суммы квадратов ошибок двух моделей, но можно рассчитать и метрики качества моделей, такие как $MSE$, $RMSE$, $MAE$ и $MAPE$.
</details>


